<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Promise关键问题 - 异常穿透 </title>

    <!-- 
        promise 异常穿透？
        (1) 当使用 promise 的 then 链式调用时，可以在最后指定失败的回调
        (2) 前面任何操作出现了异常，都会传到最后失败的回调处理
         
     -->
</head>
<body>
   
    <script >

        let p = new Promise((resolve,reject)=>{
           setTimeout(()=>{
                resolve('ok');
                // reject('Err');
           },1000);

        });

        // 执行 then 方法
        p.then(value=>{
           //console.log(111);
           throw '出错了';
        
        }).then(value =>{
            console.log(2222);
        }).then(value =>{
            console.log(3333);
        }).catch(reason =>{
            console.warn(reason);
        });        
        
    </script>
</body>

</html>